version: '3.3'

services:
  redis-app:
    container_name: redis-app
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  redis-test:
    container_name: redis-test
    image: redis:latest
    restart: always
    ports:
      - "6380:6379"
